### PR TITLE
Add notes

### PR DESCRIPTION
**Pull request by heron2014**
Related to this [issue 4](https://github.com/FAC-GM/helpers/issues/4)

@SimonLab can you please check this PR?

### CODE REVIEW

**Comment by iteles** [comment]
@heron2014 Always worth noting why a PR is closed without merging :)

**Comment by SimonLab** [comment]
We wanted to merge to the branch helpers instead of master

**Comment by iteles** [comment]
@SimonLab :+1:

**Comment by heron2014** [comment]
@iteles yeah silly mistake :)

**Pull request closed without merging**
